config/routes.rb
Rails.application.routes.draw do
  
  devise_for :students
  get 'welcome/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		 devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :last_name, :mother_last_name, :year, :cel,  :Street, :number, :colony, :delegation, :tutor, :cel_tutor, :emergency_phone, :instrument) }
		 devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :last_name, :mother_last_name, :year, :cel,  :Street, :number, :colony, :delegation, :tutor, :cel_tutor, :emergency_phone, :instrument ) }
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AMG</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>






<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

app/views/welcome/index.html.erb
<div class="row jumbotron">
  <div class="container">
    <h1 class="text-center col-xs-12 T"> Welcome </h1>




<div cloass="jumbotron">

    <div class=" text-center admin-alumno   btn-block" >
<%if student_signed_in? %>

        <div class="col-md-12 " >
            <li >
            <%= link_to "Editar", edit_student_registration_path, class:"" %> 
            </li>
            <li >
            <%= link_to "Cerrar Sesion", destroy_student_session_path, method: :delete, class:" " %> 
            </li>  
         </div>
  </div>
</div>

<%else%>
        
        <div class="col-md-12   ">
             <li id="piano" class="text-center">
            <%= link_to "Alumno", new_student_session_path, class:"btn btn-primary btn-lg " %> 
            </li>
<br><br><br>

            <li id="piano2" >
            <%= link_to "Admin", admin_user_session_path , class:"btn btn-primary btn-lg "%> 
            </li>
        </div>

<%end%>  
    </div>

</div>